stages:
  - mirror

mirror:github:
  stage: mirror
  script:
    - git push --mirror https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/romshark/ui-controls.git &> /dev/null
  tags:
    - shell-runner-01
